---
services:
  memcached:
      image: "memcached:alpine"
      ports:
          - "11211:11211"

  redis:
      image: "redis:alpine"
      ports:
          - "6379:6379"

  mongodb:
      image: "mongo:3.6"
      ports:
          - "27017:27017"
